
import { GlobalNav } from "@/components/navs.component.";
import "./globals.css";
import { NextAuthProvider } from "./providers";
import { Footer } from "@/components/footer.component";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <NextAuthProvider>
                    <GlobalNav />
                    {children}
                    <Footer />
                </NextAuthProvider>
            </body>
        </html>
    );
}
